### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by szunami**
Mostly trying to see what happens in Circle; cf https://app.asana.com/0/1176122542632172/1198881708202053

### CODE REVIEW

**Review by alex — APPROVED** [review]

**Comment by szunami** [comment]
Sadly I don't have perms to merge in this repo; those perms might help investigate the issue (or CircleCI admin perms?)? But in the short term, pls merge 4 me.

**Comment by alex** [comment]
Let me fix permissions.

**Comment by alex** [comment]
Hmm, the admin shows me that you're in a group that has write access, can you really not merge?

**Comment by alex** [comment]
Ahh, there was a screwy branch restriction on it. Should be fixed now.

**Pull request merged**
